// models/FoodTest.js
// Represents one food-testing session: a single physical ESP32 device
// testing the food for a specific donation.
//
// Lifecycle:  active → completed  (or cancelled if abandoned)
//
// Key relationships:
//   FoodTest → Donation (existing)  — resolves the correct NGO
//   FoodTest → EspDevice            — identifies the hardware
//   FoodTest → User (volunteer)     — who initiated the test
//
// The foodQualityScore (0–100) is a PROTOTYPE indicator computed from
// temperature, humidity, and MQ gas sensor readings.  It is NOT a certified
// food-safety assessment and must not be presented as such.

const mongoose = require('mongoose');

const readingSchema = new mongoose.Schema(
  {
    temperature: { type: Number, required: true }, // °C
    humidity: { type: Number, required: true },    // %
    mqValue: { type: Number, required: true },      // ADC 0–4095
    recordedAt: { type: Date, default: Date.now },
  },
  { _id: false }
);

const foodTestSchema = new mongoose.Schema(
  {
    // Human-readable test identifier (e.g. "TEST-0001").
    // Generated by the backend; never entered manually into firmware.
    testId: {
      type: String,
      required: true,
      unique: true,
      trim: true,
    },
    // The physical device that ran this test
    deviceId: {
      type: String,
      required: true,
      ref: 'EspDevice',
    },
    // Reference to the existing Donation being tested
    donationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Donation',
      required: true,
    },
    // Volunteer who initiated the test (may be null for automated/mock tests)
    volunteerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    status: {
      type: String,
      enum: ['active', 'completed', 'cancelled'],
      default: 'active',
    },
    // Raw sensor readings collected during the session
    readings: [readingSchema],
    // Final prototype food quality score (0–100).
    // Null until the test is completed.
    foodQualityScore: { type: Number, default: null, min: 0, max: 100 },
    startedAt: { type: Date, default: Date.now },
    completedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

// Index so the backend can quickly find the active test for a device
foodTestSchema.index({ deviceId: 1, status: 1 });
// Index so foodSafetyReview() can quickly look up the latest completed test
foodTestSchema.index({ donationId: 1, status: 1, completedAt: -1 });

module.exports = mongoose.model('FoodTest', foodTestSchema);
